"""Seed question bank for Quiz Master Pro.

200 questions  =  4 categories (Science, Mathematics, General Knowledge, Computer)
                x 5 levels each  x  10 questions per level.

Each entry is a tuple:
    (category, level, question, option1, option2, option3, option4, correct_index)

Difficulty increases level-wise:
    Level 1 = Very Easy, Level 2 = Easy, Level 3 = Medium,
    Level 4 = Hard,      Level 5 = Expert
"""

QUESTIONS = [
    # =========================================================
    # SCIENCE
    # =========================================================
    # --- Science Level 1 (Very Easy) ---
    ("Science", 1, "Which gas do plants absorb from the atmosphere during photosynthesis?",
     "Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen", 2),
    ("Science", 1, "What is the chemical symbol for water?",
     "O2", "CO2", "H2O", "H2", 3),
    ("Science", 1, "How many planets are there in our solar system?",
     "7", "8", "9", "10", 2),
    ("Science", 1, "What is the hardest natural substance on Earth?",
     "Gold", "Iron", "Diamond", "Quartz", 3),
    ("Science", 1, "Which organ pumps blood throughout the human body?",
     "Lungs", "Brain", "Liver", "Heart", 4),
    ("Science", 1, "What is the name of the star at the center of our solar system?",
     "Moon", "Sun", "Sirius", "Vega", 2),
    ("Science", 1, "Which of these is a liquid at room temperature?",
     "Water", "Iron", "Rock", "Ice", 1),
    ("Science", 1, "Which part of a plant makes food through photosynthesis?",
     "Roots", "Flowers", "Leaves", "Stem", 3),
    ("Science", 1, "What is the largest mammal in the world?",
     "Elephant", "Blue whale", "Giraffe", "Rhino", 2),
    ("Science", 1, "What force pulls objects toward the Earth?",
     "Friction", "Magnetism", "Gravity", "Pressure", 3),

    # --- Science Level 2 (Easy) ---
    ("Science", 2, "What is the boiling point of water at sea level?",
     "50 °C", "75 °C", "90 °C", "100 °C", 4),
    ("Science", 2, "Which planet is known as the Red Planet?",
     "Venus", "Mars", "Jupiter", "Mercury", 2),
    ("Science", 2, "Which gas do humans need to breathe to survive?",
     "Oxygen", "Carbon dioxide", "Nitrogen", "Helium", 1),
    ("Science", 2, "Which part of the cell contains the genetic material?",
     "Cytoplasm", "Cell membrane", "Nucleus", "Ribosome", 3),
    ("Science", 2, "What is often called the 'powerhouse of the cell'?",
     "Nucleus", "Mitochondria", "Golgi body", "Lysosome", 2),
    ("Science", 2, "Which vitamin is produced by the skin when exposed to sunlight?",
     "Vitamin A", "Vitamin C", "Vitamin D", "Vitamin E", 3),
    ("Science", 2, "What is the chemical formula of common table salt?",
     "KCl", "NaCl", "CaCl2", "NaHCO3", 2),
    ("Science", 2, "What is the smallest bone in the human body?",
     "Femur", "Tibia", "Stapes", "Humerus", 3),
    ("Science", 2, "Sound travels fastest in which medium?",
     "Air", "Water", "Vacuum", "Solid", 4),
    ("Science", 2, "What type of energy does a moving object possess?",
     "Potential energy", "Kinetic energy", "Chemical energy", "Thermal energy", 2),

    # --- Science Level 3 (Medium) ---
    ("Science", 3, "What is the pH value of pure water?",
     "5", "6", "7", "8", 3),
    ("Science", 3, "Which planet is famous for its prominent ring system?",
     "Mars", "Venus", "Jupiter", "Saturn", 4),
    ("Science", 3, "What is the atomic number of carbon?",
     "4", "6", "8", "12", 2),
    ("Science", 3, "Which force holds the nucleus of an atom together?",
     "Gravitational force", "Electromagnetic force", "Strong nuclear force", "Weak nuclear force", 3),
    ("Science", 3, "What is the SI unit of electrical resistance?",
     "Volt", "Ampere", "Watt", "Ohm", 4),
    ("Science", 3, "Who proposed the theory of general relativity?",
     "Isaac Newton", "Albert Einstein", "Niels Bohr", "Galileo Galilei", 2),
    ("Science", 3, "What is the chemical name of baking soda?",
     "Sodium chloride", "Sodium bicarbonate", "Calcium carbonate", "Sodium hydroxide", 2),
    ("Science", 3, "Which blood cells help the body fight infections?",
     "Red blood cells", "Platelets", "White blood cells", "Plasma cells", 3),
    ("Science", 3, "What is the scientific study of weather called?",
     "Geology", "Meteorology", "Oceanography", "Seismology", 2),
    ("Science", 3, "In which organ does most digestion and absorption of food occur?",
     "Stomach", "Large intestine", "Small intestine", "Esophagus", 3),

    # --- Science Level 4 (Hard) ---
    ("Science", 4, "What is the approximate half-life of the isotope Carbon-14?",
     "1,000 years", "3,000 years", "5,730 years", "10,000 years", 3),
    ("Science", 4, "Which metal has the highest melting point?",
     "Iron", "Tungsten", "Copper", "Platinum", 2),
    ("Science", 4, "What is the SI unit of magnetic flux?",
     "Tesla", "Gauss", "Weber", "Henry", 3),
    ("Science", 4, "Which disease is caused by a deficiency of vitamin B3 (niacin)?",
     "Scurvy", "Rickets", "Pellagra", "Beriberi", 3),
    ("Science", 4, "Which organelle is responsible for protein synthesis?",
     "Mitochondria", "Ribosome", "Lysosome", "Nucleolus", 2),
    ("Science", 4, "What is the formula for kinetic energy?",
     "mv", "mgh", "1/2 mv^2", "1/2 kx^2", 3),
    ("Science", 4, "Which type of rock forms from the cooling of magma or lava?",
     "Sedimentary", "Metamorphic", "Igneous", "Limestone", 3),
    ("Science", 4, "What is the closest star system to the Sun?",
     "Proxima Centauri system", "Barnard's Star system", "Alpha Centauri system", "Sirius system", 3),
    ("Science", 4, "What is a substance that speeds up a chemical reaction without being consumed?",
     "Reactant", "Catalyst", "Enzyme", "Solvent", 2),
    ("Science", 4, "Which layer of the atmosphere contains the ozone layer?",
     "Troposphere", "Mesosphere", "Thermosphere", "Stratosphere", 4),

    # --- Science Level 5 (Expert) ---
    ("Science", 5, "Which particles carry the weak nuclear force?",
     "Gluons", "Photons", "W and Z bosons", "Gravitons", 3),
    ("Science", 5, "Which principle states that two identical fermions cannot occupy the same quantum state?",
     "Heisenberg uncertainty principle", "Pauli exclusion principle", "Aufbau principle", "Planck principle", 2),
    ("Science", 5, "What is the molar mass of glucose (C6H12O6)?",
     "120 g/mol", "150 g/mol", "180 g/mol", "210 g/mol", 3),
    ("Science", 5, "Which cellular process produces the most ATP per glucose molecule?",
     "Glycolysis", "Krebs cycle", "Fermentation", "Oxidative phosphorylation", 4),
    ("Science", 5, "Which type of nuclear reaction powers the Sun?",
     "Nuclear fission", "Nuclear fusion", "Radioactive decay", "Electron capture", 2),
    ("Science", 5, "Which cosmological theory describes the origin of the universe?",
     "Steady state theory", "Big Bang theory", "Oscillating universe theory", "Multiverse theory", 2),
    ("Science", 5, "What is the hybridization of carbon atoms in benzene?",
     "sp", "sp2", "sp3", "sp3d", 2),
    ("Science", 5, "Which radioactive noble gas is a decay product of radium?",
     "Helium", "Neon", "Argon", "Radon", 4),
    ("Science", 5, "What does the Schrodinger equation describe?",
     "Speed of light", "Gravitational waves", "Wave function of a quantum system", "Thermal equilibrium", 3),
    ("Science", 5, "Who is credited with discovering the electron?",
     "Ernest Rutherford", "J.J. Thomson", "James Chadwick", "Robert Millikan", 2),

    # =========================================================
    # MATHEMATICS
    # =========================================================
    # --- Mathematics Level 1 (Very Easy) ---
    ("Mathematics", 1, "What is 5 + 3?",
     "6", "7", "8", "9", 3),
    ("Mathematics", 1, "What is 10 - 4?",
     "5", "6", "7", "8", 2),
    ("Mathematics", 1, "What is 2 x 3?",
     "4", "5", "6", "8", 3),
    ("Mathematics", 1, "What is 12 divided by 4?",
     "2", "3", "4", "6", 2),
    ("Mathematics", 1, "What is 7 + 6?",
     "12", "13", "14", "15", 2),
    ("Mathematics", 1, "How many sides does a triangle have?",
     "2", "3", "4", "5", 2),
    ("Mathematics", 1, "What is the next number in the sequence: 2, 4, 6, 8, ...?",
     "9", "10", "11", "12", 2),
    ("Mathematics", 1, "What is 9 - 2?",
     "6", "7", "8", "9", 2),
    ("Mathematics", 1, "How many minutes are there in one hour?",
     "30", "45", "60", "90", 3),
    ("Mathematics", 1, "What is 3 x 5?",
     "12", "14", "15", "18", 3),

    # --- Mathematics Level 2 (Easy) ---
    ("Mathematics", 2, "What is 15 + 27?",
     "40", "41", "42", "43", 3),
    ("Mathematics", 2, "What is 100 divided by 5?",
     "15", "20", "25", "30", 2),
    ("Mathematics", 2, "What is 7 x 8?",
     "54", "56", "58", "64", 2),
    ("Mathematics", 2, "What is the square of 9?",
     "72", "79", "81", "89", 3),
    ("Mathematics", 2, "What is 36 - 18?",
     "16", "17", "18", "19", 3),
    ("Mathematics", 2, "Which of these numbers is a prime number?",
     "15", "17", "21", "25", 2),
    ("Mathematics", 2, "What is 25% of 200?",
     "25", "40", "50", "75", 3),
    ("Mathematics", 2, "What is the value of 2 raised to the power 3?",
     "6", "8", "9", "12", 2),
    ("Mathematics", 2, "What is the perimeter of a square with side length 5?",
     "15", "20", "25", "30", 2),
    ("Mathematics", 2, "What is 48 divided by 6?",
     "6", "7", "8", "9", 3),

    # --- Mathematics Level 3 (Medium) ---
    ("Mathematics", 3, "What is the area of a circle with radius 7? (Use pi = 22/7)",
     "144", "150", "154", "160", 3),
    ("Mathematics", 3, "Solve for x: 2x + 6 = 14",
     "2", "3", "4", "5", 3),
    ("Mathematics", 3, "What is the value of 5 factorial (5!)?",
     "60", "100", "120", "150", 3),
    ("Mathematics", 3, "What is the sum of the interior angles of a triangle?",
     "90 degrees", "150 degrees", "180 degrees", "270 degrees", 3),
    ("Mathematics", 3, "What is the square root of 144?",
     "10", "11", "12", "13", 3),
    ("Mathematics", 3, "What is 15% of 80?",
     "10", "12", "15", "18", 2),
    ("Mathematics", 3, "What is the greatest common divisor (GCD) of 24 and 36?",
     "6", "8", "12", "18", 3),
    ("Mathematics", 3, "What is the slope of the line y = 3x + 2?",
     "2", "3", "5", "6", 2),
    ("Mathematics", 3, "What is the least common multiple (LCM) of 4 and 6?",
     "8", "12", "18", "24", 2),
    ("Mathematics", 3, "What is 0.25 written as a fraction in simplest form?",
     "1/4", "1/5", "2/5", "1/2", 1),

    # --- Mathematics Level 4 (Hard) ---
    ("Mathematics", 4, "What is the derivative of x cubed?",
     "3x", "x^2", "3x^2", "3x^3", 3),
    ("Mathematics", 4, "What is the value of log base 10 of 1000?",
     "2", "3", "4", "1000", 2),
    ("Mathematics", 4, "What is the sum of the interior angles of a hexagon?",
     "540 degrees", "600 degrees", "720 degrees", "900 degrees", 3),
    ("Mathematics", 4, "What are the solutions of the equation x^2 - 9 = 0?",
     "x = 3 only", "x = -3 only", "x = 3 and x = -3", "x = 9 only", 3),
    ("Mathematics", 4, "What is the value of sin(30 degrees)?",
     "1/2", "1/4", "3/4", "1", 1),
    ("Mathematics", 4, "What is the 6th term of the Fibonacci sequence that starts 1, 1, ...?",
     "5", "8", "13", "21", 2),
    ("Mathematics", 4, "What is the probability of rolling a total of 7 with two fair dice?",
     "1/6", "1/9", "5/36", "1/12", 1),
    ("Mathematics", 4, "What is the area of a triangle with base 10 and height 12?",
     "60", "70", "80", "120", 1),
    ("Mathematics", 4, "What is the value of 2 raised to the power 10?",
     "512", "1024", "2048", "4096", 2),
    ("Mathematics", 4, "What is the indefinite integral of 2x with respect to x?",
     "2x + C", "x^2 + C", "2x^2 + C", "x + C", 2),

    # --- Mathematics Level 5 (Expert) ---
    ("Mathematics", 5, "What is the limit of sin(x)/x as x approaches 0?",
     "0", "1", "Infinity", "Does not exist", 2),
    ("Mathematics", 5, "What is the determinant of the matrix [[1, 2], [3, 4]]?",
     "-2", "2", "-1", "4", 1),
    ("Mathematics", 5, "What is the value of the mathematical constant e rounded to 3 decimal places?",
     "2.712", "2.718", "2.723", "3.142", 2),
    ("Mathematics", 5, "What is the sum of the infinite geometric series 1 + 1/2 + 1/4 + ...?",
     "1.5", "1.75", "2", "4", 3),
    ("Mathematics", 5, "What is the 10th term of the arithmetic sequence 3, 7, 11, ...?",
     "35", "37", "39", "41", 3),
    ("Mathematics", 5, "What is the indefinite integral of e^x with respect to x?",
     "e^x + C", "x * e^x + C", "e^(x+1) + C", "ln(x) + C", 1),
    ("Mathematics", 5, "What is the second derivative of f(x) = x^4?",
     "4x^3", "12x^2", "24x", "12x", 2),
    ("Mathematics", 5, "How many ways can 5 distinct books be arranged on a shelf?",
     "60", "100", "120", "720", 3),
    ("Mathematics", 5, "What is the probability that a random integer from 1 to 100 is divisible by 7?",
     "10%", "14%", "17%", "21%", 2),
    ("Mathematics", 5, "Which number is a perfect square, a perfect cube and a power of two?",
     "16", "64", "81", "128", 2),

    # =========================================================
    # GENERAL KNOWLEDGE
    # =========================================================
    # --- General Knowledge Level 1 (Very Easy) ---
    ("General Knowledge", 1, "What is the capital city of France?",
     "London", "Paris", "Berlin", "Madrid", 2),
    ("General Knowledge", 1, "How many continents are there on Earth?",
     "5", "6", "7", "8", 3),
    ("General Knowledge", 1, "What is the largest ocean on Earth?",
     "Atlantic", "Indian", "Arctic", "Pacific", 4),
    ("General Knowledge", 1, "Which country is known as the Land of the Rising Sun?",
     "China", "Japan", "South Korea", "Thailand", 2),
    ("General Knowledge", 1, "How many colors are there in a rainbow?",
     "5", "6", "7", "8", 3),
    ("General Knowledge", 1, "What is the currency of the United States?",
     "Euro", "Pound", "Dollar", "Yen", 3),
    ("General Knowledge", 1, "What is the largest continent on Earth?",
     "Africa", "Asia", "Europe", "North America", 2),
    ("General Knowledge", 1, "What is the tallest animal on Earth?",
     "Elephant", "Giraffe", "Hippo", "Ostrich", 2),
    ("General Knowledge", 1, "How many days are there in a leap year?",
     "365", "366", "367", "364", 2),
    ("General Knowledge", 1, "Which fairy-tale character lost a glass slipper?",
     "Snow White", "Sleeping Beauty", "Cinderella", "Rapunzel", 3),

    # --- General Knowledge Level 2 (Easy) ---
    ("General Knowledge", 2, "Which is often considered the longest river in the world?",
     "Amazon", "Nile", "Yangtze", "Mississippi", 2),
    ("General Knowledge", 2, "Who wrote the play 'Romeo and Juliet'?",
     "Charles Dickens", "William Shakespeare", "Mark Twain", "Jane Austen", 2),
    ("General Knowledge", 2, "In which country is the Taj Mahal located?",
     "Nepal", "Pakistan", "India", "Bangladesh", 3),
    ("General Knowledge", 2, "Which is the largest hot desert in the world?",
     "Gobi", "Kalahari", "Sahara", "Thar", 3),
    ("General Knowledge", 2, "What is the smallest country in the world?",
     "Monaco", "Malta", "Vatican City", "San Marino", 3),
    ("General Knowledge", 2, "Who painted the Mona Lisa?",
     "Pablo Picasso", "Leonardo da Vinci", "Vincent van Gogh", "Michelangelo", 2),
    ("General Knowledge", 2, "What is the capital city of Australia?",
     "Sydney", "Melbourne", "Canberra", "Perth", 3),
    ("General Knowledge", 2, "How many players are there on a standard soccer team on the field?",
     "9", "10", "11", "12", 3),
    ("General Knowledge", 2, "Which element has the chemical symbol 'Au'?",
     "Silver", "Gold", "Aluminium", "Argon", 2),
    ("General Knowledge", 2, "What is the largest galaxy in the Local Group?",
     "Milky Way", "Andromeda", "Triangulum", "Sombrero", 2),

    # --- General Knowledge Level 3 (Medium) ---
    ("General Knowledge", 3, "What is the highest mountain in the world?",
     "K2", "Kangchenjunga", "Mount Everest", "Lhotse", 3),
    ("General Knowledge", 3, "What is the largest island in the world?",
     "Borneo", "Madagascar", "New Guinea", "Greenland", 4),
    ("General Knowledge", 3, "What is the currency of Japan?",
     "Won", "Yen", "Yuan", "Ringgit", 2),
    ("General Knowledge", 3, "How many bones are there in the adult human body?",
     "186", "196", "206", "216", 3),
    ("General Knowledge", 3, "Which river flows through the city of Paris?",
     "Rhine", "Seine", "Loire", "Thames", 2),
    ("General Knowledge", 3, "What is the fastest land animal?",
     "Lion", "Cheetah", "Leopard", "Horse", 2),
    ("General Knowledge", 3, "What is the largest organ of the human body?",
     "Liver", "Brain", "Skin", "Lungs", 3),
    ("General Knowledge", 3, "Which language has the most native speakers in the world?",
     "English", "Spanish", "Hindi", "Mandarin Chinese", 4),
    ("General Knowledge", 3, "What is the study of stars and celestial bodies called?",
     "Geology", "Astronomy", "Meteorology", "Biology", 2),
    ("General Knowledge", 3, "Which country is famous for the Great Barrier Reef?",
     "New Zealand", "Australia", "Philippines", "Fiji", 2),

    # --- General Knowledge Level 4 (Hard) ---
    ("General Knowledge", 4, "What is the world's longest mountain range?",
     "Himalayas", "Rockies", "Andes", "Alps", 3),
    ("General Knowledge", 4, "Which country is the world's largest producer of coffee?",
     "Colombia", "Ethiopia", "Vietnam", "Brazil", 4),
    ("General Knowledge", 4, "What is the deepest point in the world's oceans?",
     "Java Trench", "Mariana Trench", "Tonga Trench", "Puerto Rico Trench", 2),
    ("General Knowledge", 4, "Which is the only continent with no permanent human population?",
     "Australia", "South America", "Antarctica", "Arctic", 3),
    ("General Knowledge", 4, "What is the capital city of Canada?",
     "Toronto", "Vancouver", "Montreal", "Ottawa", 4),
    ("General Knowledge", 4, "What is the national animal of Australia?",
     "Koala", "Kangaroo", "Emu", "Echidna", 2),
    ("General Knowledge", 4, "Which country currently has the largest population in the world?",
     "China", "United States", "Indonesia", "India", 4),
    ("General Knowledge", 4, "What is the world's largest coral reef system?",
     "Great Barrier Reef", "Red Sea Coral Reef", "Belize Barrier Reef", "New Caledonia Barrier Reef", 1),
    ("General Knowledge", 4, "Which famous artist is known for cutting off his own ear?",
     "Claude Monet", "Vincent van Gogh", "Pablo Picasso", "Salvador Dali", 2),
    ("General Knowledge", 4, "Which country is the world's largest island country by area?",
     "Japan", "New Zealand", "Indonesia", "United Kingdom", 3),

    # --- General Knowledge Level 5 (Expert) ---
    ("General Knowledge", 5, "Which is generally recognized as the oldest university in the world?",
     "University of Bologna", "University of Oxford", "University of Al-Qarawiyyin", "Al-Azhar University", 3),
    ("General Knowledge", 5, "Which country has more pyramids than Egypt?",
     "Mexico", "Sudan", "Peru", "China", 2),
    ("General Knowledge", 5, "Which city is famously known as the 'City of Canals'?",
     "Amsterdam", "Bangkok", "Venice", "Stockholm", 3),
    ("General Knowledge", 5, "Which country has the most lakes in the world?",
     "Russia", "United States", "Finland", "Canada", 4),
    ("General Knowledge", 5, "What is the driest place on Earth?",
     "Sahara Desert", "Atacama Desert", "Gobi Desert", "Death Valley", 2),
    ("General Knowledge", 5, "Which ancient Wonder of the World still exists today?",
     "Hanging Gardens of Babylon", "Colossus of Rhodes", "Great Pyramid of Giza", "Lighthouse of Alexandria", 3),
    ("General Knowledge", 5, "What is the largest lake in the world by area?",
     "Lake Superior", "Lake Victoria", "Caspian Sea", "Lake Baikal", 3),
    ("General Knowledge", 5, "What is the national sport of Japan?",
     "Karate", "Sumo wrestling", "Judo", "Baseball", 2),
    ("General Knowledge", 5, "Which is the largest freshwater lake in the world by volume?",
     "Lake Superior", "Lake Baikal", "Lake Tanganyika", "Lake Michigan", 2),
    ("General Knowledge", 5, "Which country has the most natural lakes exceeding 1,000 square km?",
     "Canada", "United States", "Russia", "India", 1),

    # =========================================================
    # COMPUTER
    # =========================================================
    # --- Computer Level 1 (Very Easy) ---
    ("Computer", 1, "What does CPU stand for?",
     "Central Processing Unit", "Computer Personal Unit", "Central Program Utility", "Core Processing Unit", 1),
    ("Computer", 1, "Which device is used to type text into a computer?",
     "Mouse", "Keyboard", "Monitor", "Scanner", 2),
    ("Computer", 1, "What does 'www' stand for in a web address?",
     "World Wide Web", "World Wide Work", "Web World Wide", "Wide World Web", 1),
    ("Computer", 1, "Which of these is an operating system?",
     "Windows", "Microsoft Word", "Google Chrome", "Photoshop", 1),
    ("Computer", 1, "What does RAM stand for?",
     "Random Access Memory", "Read And Modify", "Rapid Access Memory", "Random Allocation Module", 1),
    ("Computer", 1, "Which device is used to move the cursor on a screen?",
     "Keyboard", "Joystick", "Mouse", "Printer", 3),
    ("Computer", 1, "How many bytes are there in 1 kilobyte (KB)?",
     "100", "512", "1024", "2048", 3),
    ("Computer", 1, "Which of these is a popular search engine?",
     "Photoshop", "Google", "Windows", "Excel", 2),
    ("Computer", 1, "What is the screen of a desktop computer called?",
     "Keyboard", "Monitor", "Processor", "Motherboard", 2),
    ("Computer", 1, "Which device connects a home network to the internet?",
     "Router", "Monitor", "Printer", "Scanner", 1),

    # --- Computer Level 2 (Easy) ---
    ("Computer", 2, "What does HTML stand for?",
     "HyperText Markup Language", "HighText Machine Language", "Hyperlink Text Module Language", "Home Tool Markup Language", 1),
    ("Computer", 2, "Which company created the Windows operating system?",
     "Apple", "IBM", "Microsoft", "Google", 3),
    ("Computer", 2, "What is the main circuit board of a computer called?",
     "Processor", "Motherboard", "Hard drive", "Power supply", 2),
    ("Computer", 2, "What does URL stand for?",
     "Uniform Resource Locator", "Universal Remote Link", "Unique Resource Locator", "Unified Routing Language", 1),
    ("Computer", 2, "Which of these is NOT a programming language?",
     "Python", "Java", "C++", "HTML", 4),
    ("Computer", 2, "What is often called the 'brain' of the computer?",
     "RAM", "Hard disk", "CPU", "GPU", 3),
    ("Computer", 2, "Which device stores data permanently using spinning magnetic disks?",
     "SSD", "RAM", "HDD", "Cache", 3),
    ("Computer", 2, "What does GPS stand for?",
     "Global Positioning System", "General Positioning System", "Global Path System", "Geographic Point Service", 1),
    ("Computer", 2, "Which of these is an image file format?",
     "MP3", "JPEG", "PDF", "DOCX", 2),
    ("Computer", 2, "What is a web browser used for?",
     "Editing photos", "Viewing websites", "Writing documents", "Calculating spreadsheets", 2),

    # --- Computer Level 3 (Medium) ---
    ("Computer", 3, "What does CSS stand for?",
     "Computer Style Sheets", "Cascading Style Sheets", "Creative Style System", "Coded Styling Source", 2),
    ("Computer", 3, "Which data structure follows the FIFO (First In, First Out) principle?",
     "Stack", "Array", "Queue", "Tree", 3),
    ("Computer", 3, "What does SQL stand for?",
     "Structured Query Language", "Sequential Query Logic", "Simple Question Language", "Standard Query Loop", 1),
    ("Computer", 3, "What is the decimal value of the binary number 101?",
     "3", "4", "5", "6", 3),
    ("Computer", 3, "Which of these is a version control system?",
     "Git", "Slack", "Zoom", "Docker", 1),
    ("Computer", 3, "What does DNS stand for?",
     "Dynamic Network System", "Domain Name System", "Digital Name Server", "Distributed Network Service", 2),
    ("Computer", 3, "Which type of software is an operating system?",
     "Application software", "System software", "Utility software", "Malware", 2),
    ("Computer", 3, "What is the base of the hexadecimal number system?",
     "8", "10", "16", "32", 3),
    ("Computer", 3, "What does HTTP stand for?",
     "HyperText Transfer Protocol", "High Tech Transfer Process", "Hyperlink Text Tool Protocol", "Host Transfer Protocol", 1),
    ("Computer", 3, "Which language is primarily used to structure content on web pages?",
     "Python", "HTML", "Java", "SQL", 2),

    # --- Computer Level 4 (Hard) ---
    ("Computer", 4, "Which sorting algorithm has an average-case time complexity of O(n log n)?",
     "Bubble sort", "Insertion sort", "Quick sort", "Selection sort", 3),
    ("Computer", 4, "What does OOP stand for?",
     "Object-Oriented Programming", "Ordered Operation Process", "Open Object Protocol", "Output Optimization Program", 1),
    ("Computer", 4, "In Python, which keyword is used to define a function?",
     "func", "function", "def", "lambda", 3),
    ("Computer", 4, "What is the time complexity of binary search on a sorted array?",
     "O(n)", "O(log n)", "O(n log n)", "O(n^2)", 2),
    ("Computer", 4, "Which protocol is used to send email?",
     "HTTP", "FTP", "SMTP", "SNMP", 3),
    ("Computer", 4, "What does TCP stand for?",
     "Transfer Control Process", "Transmission Control Protocol", "Total Communication Protocol", "Terminal Control Program", 2),
    ("Computer", 4, "Which of these is a NoSQL database?",
     "MySQL", "PostgreSQL", "MongoDB", "SQLite", 3),
    ("Computer", 4, "In computer networking, what does IP stand for?",
     "Internet Protocol", "Internal Process", "Input Port", "Interface Package", 1),
    ("Computer", 4, "Which data structure works on the LIFO (Last In, First Out) principle?",
     "Queue", "Stack", "Heap", "Linked list", 2),
    ("Computer", 4, "What is a cache in a computer system?",
     "A type of malware", "High-speed temporary storage", "A networking cable", "A printer driver", 2),

    # --- Computer Level 5 (Expert) ---
    ("Computer", 5, "Which algorithm is commonly recommended for securely hashing passwords?",
     "MD5", "SHA-1", "bcrypt", "Base64", 3),
    ("Computer", 5, "What does the ACID acronym stand for in database systems?",
     "Atomicity, Consistency, Isolation, Durability",
     "Accuracy, Clarity, Integrity, Data",
     "Access, Control, Index, Deletion",
     "Automated, Concurrent, Integrated, Distributed", 1),
    ("Computer", 5, "In a binary tree, what is a node with no children called?",
     "Root", "Leaf", "Internal node", "Edge", 2),
    ("Computer", 5, "Which attack involves injecting malicious code into SQL queries?",
     "Cross-site scripting", "SQL injection", "Phishing", "Denial of service", 2),
    ("Computer", 5, "What is the worst-case time complexity of quicksort?",
     "O(n log n)", "O(n)", "O(n^2)", "O(log n)", 3),
    ("Computer", 5, "How many layers are there in the OSI reference model?",
     "5", "6", "7", "8", 3),
    ("Computer", 5, "Which transport protocol is connectionless?",
     "TCP", "UDP", "HTTP", "FTP", 2),
    ("Computer", 5, "What does AES stand for?",
     "Automated Encryption Standard", "Advanced Encryption Standard", "Advanced Encoding System", "Atomic Encryption Scheme", 2),
    ("Computer", 5, "In machine learning, what is 'overfitting'?",
     "Model is too simple to learn the data",
     "Model performs well on training data but poorly on new data",
     "Model trains too slowly",
     "Model uses too much memory", 2),
    ("Computer", 5, "What is the average time complexity of accessing an element in a hash table?",
     "O(n)", "O(log n)", "O(1)", "O(n log n)", 3),
]
